[package]
name = "derive_macro_tool"
version = "0.1.0"
authors = ["tacogips <me@tacogips.me>"]
edition = "2018"


[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = {version = "1.0",features =["extra-traits","clone-impls"]}
chrono = {version = "0.4", features = ["clock"]}
