[package]
name = "async-graphql-reverse"
version = "0.1.0"
authors = ["tacogips <me@tacogips.me>"]
edition = "2018"

[[bin]]
name = "async-graphql-reverse"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0"
async-graphql = "2.9"
async-graphql-parser = "2.9"
clap = "3.0.0-beta.2"
env_logger = "0.8"
log = "0.4"
structopt = "0.3"
