[tasks.test-run]
command = "cargo"
args = ["run","--bin", "async-graphql-reverse","--","--input-schema","examples/simple/input/schema.graphql","--output-dir","examples/simple/output","--config","examples/simple/input/reverse.toml"]

