default_data_source_fetch_method = "ctx.data_unchecked::<DataSource>()"

# custom_member_types=["CustomPrimitiveType"]

[using]
data_source = "use crate::datasource::DataSource"


[[resolver]]
target_type = "Query"
target_field = "type"
resolver_type = "method" ## "method" or "member"

[[resolver]]
target_type = "Friend"
target_field = "name"
resolver_type = "method"


[[custom_resolver]]
target_type ="Query"
body ="""
    pub async fn custom_resolver(&self, ctx: &Context<'_>) -> Result<Option<String>> {
        ctx.data_unchecked::<DataSource>()
            .query_custom_resolver(&ctx, self)
            .await
    }
"""
#using = "use std::fs"
